### ISSUE TITLE
cloudstorage api change?

### ISSUE THREAD

**Issue by vessenes** [tchaik/tchaik#58]
From a totally fresh install:

```
# go get -v
tchaik.com/store
# tchaik.com/store
./cloudstorage.go:43: undefined: "google.golang.org/cloud/storage".StatObject
./cloudstorage.go:48: undefined: "google.golang.org/cloud/storage".NewReader
```

The repos linked to don't seem to provide those functions anymore from the docs, at least.

**Comment by dhowden** [comment]
Good spot!  I have a fix, will push when it has been properly tested.

**Comment by vessenes** [comment]
Cool! I'll try it out and see how it looks over here.

**Comment by dhowden** [comment]
Unfortuantely my test account has stopped working (trial expired!), so I'm just getting errors about that at the moment.  Will have more time to create another account at the weekend, but if you can look now that would be great.

I suspect that there will be an issue since I'm no longer passing the `ProjectID` through (there doesn't seem to be a way to do this in the new API, and a quick scan over the examples doesn't seem to provide an answer!
